const STATUS = {
	IN_LOBBY: 'IN_LOBBY',
	JOIN: 'JOIN',
	CREATE: 'CREATE',
	FULL: 'FULL',
	APPROVE: 'APPROVE',
	CONNECTING: 'CONNECTING',
	ESTABLISHED: 'ESTABLISHED',
	HOST_HANGUP: 'HOST_HANGUP',
	GUEST_HANGUP: 'GUEST_HANGUP'
};
export default STATUS;
