export const USER_STATUS = {
  GETTING_ROOM: 'GETTING_ROOM',
  IN_LOBBY: 'IN_LOBBY',
  IN_GAME: 'IN_GAME',
};

export const RTC_STATUS = {
  OFF: 'OFF',
  JOIN: 'JOIN',
  CREATE: 'CREATE',
  APPROVE: 'APPROVE',
  FULL: 'FULL',
  CONNECTING: 'CONNECTING',
  ESTABLISHED: 'ESTABLISHED',
  HOST_HANGUP: 'HOST_HANGUP',
  GUEST_HANGUP: 'GUEST_HANGUP',
};
