const STATUS = {
  GETTING_ROOM: 'GETTING_ROOM',
  IN_LOBBY: 'IN_LOBBY',
  READY: 'READY',
  JOIN: 'JOIN',
  CREATE: 'CREATE',
  FULL: 'FULL',
  APPROVE: 'APPROVE',
  CONNECTING: 'CONNECTING',
  ESTABLISHED: 'ESTABLISHED',
  HOST_HANGUP: 'HOST_HANGUP',
  GUEST_HANGUP: 'GUEST_HANGUP',
};
export default STATUS;
